// app/views/Splash.tsx
import { Component, For, Match, Show, Switch, createEffect, createResource, createSignal } from "solid-js"
import { Transition } from "solid-transition-group"
import { i18n } from "../assets/translations"
import { KeyboardArrowUpOutline } from "../components/svg+path/KeyboardArrowUpOutline"
import { PauseCircleOutline } from "../components/svg+path/PauseCircleOutline"
import { PlayCircleOutline } from "../components/svg+path/PlayCircleOutline"
import { RainyOutline } from "../components/svg+path/RainyOutline"
import { createRainvillePlayer } from "../models/RainvillePlayer"

const LoadingSpinner: Component = () => (
    <div class="flex absolute w-100% h-100% justify-center items-center">
        <div class="w-10 mobile:w-15 h-10 mobile:h-15 border-5 rounded-50% border-[#FFFFFFAF_#FFFFFFAF_#4FAFFFAF_#FFFFFFAF] animate-spin animate-duration-1000" />
    </div>
)

export const Splash: Component = () => {
    const [rainvillePlayerResource] = createResource(createRainvillePlayer)
    createEffect(() => rainvillePlayerResource.error && location.reload())

    const [paused, setPaused] = createSignal(true)
    createEffect(() => {
        if (!rainvillePlayerResource.loading && !rainvillePlayerResource.error && rainvillePlayerResource.latest) {
            rainvillePlayerResource.latest.paused = paused()
        }
    })

    const [menuIsOpened, setMenuIsOpened] = createSignal(false)

    return (
        <div class="relative w-100% h-100% bg-gray-300">
            <Switch>
                <Match when={rainvillePlayerResource.loading}>
                    <LoadingSpinner />
                </Match>
                <Match when={rainvillePlayerResource.latest}>
                    <div
                        data-tauri-drag-region
                        class="flex flex-col absolute w-100% h-100% justify-center items-center"
                    >
                        <svg
                            class="w-14 mobile:w-21 h-14 mobile:h-21 fill-current text-gray-500"
                            height="48"
                            viewBox="0 -960 960 960"
                            width="48"
                        >
                            <RainyOutline />
                        </svg>
                        <div class="pb-4" />
                        <button class="bg-transparent" onClick={() => setPaused(!paused())} disabled={menuIsOpened()}>
                            <svg
                                class="w-7.5 mobile:w-11.25 h-7.5 mobile:h-11.25 fill-current text-gray-500"
                                height="48"
                                viewBox="0 -960 960 960"
                                width="48"
                            >
                                <Show when={paused()} fallback={<PauseCircleOutline />}>
                                    <PlayCircleOutline />
                                </Show>
                            </svg>
                        </button>
                    </div>
                    <div class="flex absolute bottom-0 p-3 mobile:p-4.5 w-100% justify-center items-center">
                        <button
                            class="bg-transparent"
                            onClick={() => setMenuIsOpened(!menuIsOpened())}
                            disabled={menuIsOpened()}
                        >
                            <svg
                                class="w-7.5 mobile:w-11.25 h-7.5 mobile:h-11.25 fill-current text-gray-500"
                                height="48"
                                viewBox="0 -960 960 960"
                                width="48"
                            >
                                <KeyboardArrowUpOutline />
                            </svg>
                        </button>
                    </div>
                    <Transition
                        onEnter={(el, done) => {
                            const a = el.animate([{ opacity: 0 }, { opacity: 1 }], {
                                duration: 300
                            })
                            const b = el.children[0]!.animate(
                                [{ transform: "translateY(100%)" }, { transform: "translateY(0%)" }],
                                {
                                    duration: 300,
                                    easing: "ease-out"
                                }
                            )
                            Promise.all([a.finished, b.finished]).then(done)
                        }}
                        onExit={(el, done) => {
                            const a = el.animate([{ opacity: 1 }, { opacity: 0 }], {
                                duration: 300
                            })
                            const b = el.children[0]!.animate(
                                [{ transform: "translateY(0%)" }, { transform: "translateY(100%)" }],
                                {
                                    duration: 300,
                                    easing: "ease-in"
                                }
                            )
                            Promise.all([a.finished, b.finished]).then(done)
                        }}
                    >
                        <Show when={menuIsOpened()}>
                            <div
                                data-tauri-drag-region
                                class="absolute w-100% h-100% bg-[#00103033] focus:bg-[#00103066]"
                                style="-webkit-tap-highlight-color: #00000000;"
                                role="button"
                                tabindex={0}
                                onClick={() => setMenuIsOpened(false)}
                            >
                                <div class="absolute bottom-0 w-100% h-50% overflow-scroll bg-[#FFFFFC] rounded-t-lg border-0.5 border-[#EFEFCF] drop-shadow-2xl drop-shadow-color-[#00103026] px-2 mobile:px-2.5 py-2.5 mobile:py-3.125">
                                    <For each={rainvillePlayerResource.latest!.tracks}>
                                        {(track, index) => (
                                            <div
                                                role="button"
                                                class="px-2 mobile:px-2.5 py-2.5 mobile:py-3.125"
                                                onClick={() => (rainvillePlayerResource.latest!.trackNum = index())}
                                            >
                                                <span class="text-gray-700 font-300 text-16px mobile:text-20px">
                                                    {i18n().t(track[0])}
                                                </span>
                                            </div>
                                        )}
                                    </For>
                                </div>
                            </div>
                        </Show>
                    </Transition>
                </Match>
            </Switch>
        </div>
    )
}

// app/views/Splash.svelte
<script lang="ts">
    import IconButton from "@smui/icon-button"
    import List, { Item as ListItem, Text as ListText } from "@smui/list"
    import { onDestroy } from "svelte"
    import { fade, slide } from "svelte/transition"
    import { createRainvillePlayer } from "../models/RainvillePlayer"

    const playerPromise = createRainvillePlayer()

    let menuIsOpen = false

    onDestroy(() => playerPromise.then((player) => player.handleDestroy()))
</script>

<div class="relative w-100% h-100% bg-gray-300">
    {#await playerPromise}
        <div class="flex absolute w-100% h-100% justify-center items-center">
            <!-- Loading Spinner -->
            <div
                class="w-10 h-10 border-5 rounded-50% border-[#FFFFFFAF_#FFFFFFAF_#4FAFFFAF_#FFFFFFAF] animate-spin animate-duration-1000"
            />
        </div>
    {:then player}
        <div data-tauri-drag-region class="flex flex-col absolute w-100% h-100% justify-center items-center">
            <svg class="w-14 h-14 fill-current text-gray-500" height="48" viewBox="0 -960 960 960" width="48">
                <!-- Material Symbol - Rainy -->
                <path
                    d="M558-83q-11 5-23.5 1T517-97l-69-138q-5-11-1.5-23.5T461-276q11-5 23.5-1t17.5 15l69 138q5 11 1.5 23.5T558-83Zm240-1q-11 5-23.5 1T757-98l-69-138q-5-11-1.5-23.5T701-277q11-5 23.5-1t17.5 15l69 138q5 11 1.5 23.5T798-84Zm-480 0q-11 5-23.5 1.5T277-97l-69-138q-5-11-1-23.5t15-17.5q11-5 23.5-1.5T263-263l69 139q5 11 1 23t-15 17Zm-28-256q-87 0-148.5-61.5T80-550q0-79 56.5-141T277-759q32-56 84.5-88.5T480-880q91 0 152.5 57.5T708-680q79 4 125.5 53.5T880-510q0 70-49.5 120T710-340H290Zm0-60h420q46 0 78-32.5t32-77.5q0-46-32-78t-78-32h-60v-30q0-71-49.5-120.5T480-820q-51 0-93.5 27.5T324-718l-8 18h-28q-62 2-105 45.5T140-550q0 62 44 106t106 44Zm190-210Z"
                />
            </svg>
            <div class="pb-4" />
            <IconButton
                class="material-icons text-3xl text-gray-500"
                on:click={() => (player.paused = !player.paused)}
                disabled={menuIsOpen}
            >
                {player.paused ? "play_circle_outline" : "pause_circle"}
            </IconButton>
        </div>
        <div class="flex absolute bottom-0 p-1 w-100% justify-center items-center">
            <IconButton
                class="material-icons text-3xl text-gray-500"
                on:click={() => (menuIsOpen = !menuIsOpen)}
                disabled={menuIsOpen}
            >
                keyboard_arrow_up
            </IconButton>
        </div>
        {#if menuIsOpen}
            <div
                data-tauri-drag-region
                class="absolute w-100% h-100% bg-[#00103033] focus:bg-[#00103066]"
                style:-webkit-tap-highlight-color="#00000000"
                role="button"
                tabindex={0}
                on:keypress={(event) => event.key == "Enter" && (menuIsOpen = false)}
                on:click={() => (menuIsOpen = false)}
                transition:fade
            >
                <div
                    class="absolute bottom-0 w-100% h-50% overflow-scroll bg-[#FFFFFC] rounded-t-lg border-0.5 border-[#EFEFCF] drop-shadow-2xl drop-shadow-color-[#00103026]"
                    transition:slide={{ axis: "y" }}
                >
                    <List>
                        {#each player.tracks as [trackName], index}
                            <ListItem
                                class="mobile:text-0.75rem mobile:py-5"
                                on:SMUI:action={() => (player.trackNum = index)}
                            >
                                <ListText class={player.trackNum == index ? "text-[var(--mdc-theme-primary)]" : ""}>
                                    {trackName}
                                </ListText>
                            </ListItem>
                        {/each}
                    </List>
                </div>
            </div>
        {/if}
    {/await}
</div>
